# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build EXE

on:
  workflow_dispatch:
  push:
    tags: 
    - 'v*'
  pull_request:
    branches: [ "github" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
     - uses: actions/checkout@v3
     - name: Install Python, pipenv and Pipfile packages
       uses: palewire/install-python-pipenv-pipfile@v2
       with:
        python-version: 3.7.5
     - name: Install Package
       run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
     - name: Start Build 
       run: |
        pip list
        python build.py
     - name: package
       run: |
        mkdir package
        cp dist/*.exe package/
        cp tmall_tmpl.xlsx package/
        cd package
        7z a -tzip main.zip main.exe tmall_tmpl.xlsx
        cd ..
     - name: upload artifacts
       uses: actions/upload-artifact@v2
       with:
         name: update 
         path: |
          package/main.zip
     - name: release
       uses: softprops/action-gh-release@v1
       with:
        files: |
         package/main.zip
        echo: success
